### ISSUE TITLE
about a istio configuration  on blog

### ISSUE THREAD

**Issue by linkingli** [vadimeisenbergibm/istio-tutorial#1]
sir,sorry to comment this msg on this repo,but,Recently, I read a blog from istio Official website，which like following,you said--"which instructs the gateway to pass the ingress traffic AS IS, without terminating TLS."
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: proxy
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - httpbin.org
  - port:
      number: 443
      name: tls
      protocol: TLS
    tls:
      mode: PASSTHROUGH
    hosts:
    - edition.cnn.com
```
so there is a tls config,its make sense,then i see like this
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: localhost
spec:
  host: localhost.local
  trafficPolicy:
    tls:
      mode: DISABLE
      sni: localhost.local
```
:(,so you let traffic go throuh istio  with PASSTHROUGH，why you write mode: DISABLE like this?
